name: Java CICD

on:
  push:
    branches: [main, phase05]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"

      - name: Build with Maven
        working-directory: ./Phase01_Full-Text Search
        run: mvn --batch-mode --update-snapshots package

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"

      - name: Run the Maven verify phase
        working-directory: ./Phase01_Full-Text Search
        run: mvn --batch-mode --update-snapshots verify
